def print_menu():
    print('*'*40)
    print(' Warehouse Control System')
    print('*'*40)

    print('[1] Register New Item')
    print('[2] List All Items')
    print('[3] Update Stock')
    print('[4] List Items With No Stock')
    print('[5] View items By Category')
    print('[6] Delete Item')
    print('[7] View Stock Value')
    print('[8] Register Purchase')
    print('[9] Register A Sale')
    print('[10] See Log Of Events')
    print('[x] Exit')